services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
    command: sleep infinity
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/agent_discovery
      - PYTHONPATH=/workspace
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    network_mode: host

    # To run directly on MacOS, comment out the network_mode: host line above and uncomment the ports line below
#    ports:
#      - "8000:8000"

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./.devcontainer/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: agent_discovery
    network_mode: host

    # To run directly on MacOS, comment out the network_mode: host line above and uncomment the ports line below
#    ports:
#      - "5432:5432"

volumes:
  postgres-data:
